---
name: Date-MSD
version: 0.001
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: conversion between flavours of Mars Sol Date
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
conflicts:
  Math::BigRat: < 0.04
dynamic_config: 0
provides:
  Date::MSD:
    file: lib/Date/MSD.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
