# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-MSD
version:      0.000
version_from: lib/Date/MSD.pm
installdirs:  site
requires:
    Math::BigRat:                  0.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
